# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "thunderbolt"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  boot.kernelParams = [
    "pci=realloc" # enable dynamic pci allocation to handle 14+ usb ports
  ];
  hardware.cpu.amd.updateMicrocode = true;

  boot.initrd.luks.devices = {
    "pool0n0-decrypted" = {
      device = "/dev/disk/by-uuid/ff2679c1-748d-4959-b933-b041c08e6bdc";
      allowDiscards = true;
    };
    "pool0n1-decrypted" = {
      device = "/dev/disk/by-uuid/8a613bfb-9307-467b-8223-91ef83de824c";
      allowDiscards = true;
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/pool0n0-decrypted";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd"
        "noatime"
      ];
    };
    "/nix" = {
      device = "/dev/mapper/pool0n0-decrypted";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd"
        "noatime"
      ];
    };
    "/persist" = {
      device = "/dev/mapper/pool0n0-decrypted";
      fsType = "btrfs";
      options = [
        "subvol=persist"
        "compress=zstd"
        "noatime"
      ];
      neededForBoot = true;
    };
    "/var/log" = {
      device = "/dev/mapper/pool0n0-decrypted";
      fsType = "btrfs";
      options = [
        "subvol=log"
        "compress=zstd"
        "noatime"
      ];
      neededForBoot = true;
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/62D1-20D7";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1f1e0cb5-a2ce-4c64-8f50-ac7b480bbb9b"; }
    { device = "/dev/disk/by-uuid/2381cb89-7a16-4784-b965-01edbd4e3faf"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
